//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCabana.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int IDReserva { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public double PrecioTotal { get; set; }
        public double PrecioActividades { get; set; }
        public double Descuento { get; set; }
        public int CedulaEmpleado { get; set; }
        public int CedulaUsuario { get; set; }
        public int IDActividad { get; set; }
        public int IDHabitacion { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Habitacion Habitacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
